//
//  WeatherInfoInteractor.swift
//  DarkSkyWeather
//
//  Created by rowkaxl on 10/08/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol WeatherInfoBusinessLogic {
    func doSomething(request: WeatherInfo.Something.Request)
}

protocol WeatherInfoDataStore {
    var pageIndex: Int { get set }
    var placemark: MKPlacemark? { get set }
}

class WeatherInfoInteractor: WeatherInfoBusinessLogic, WeatherInfoDataStore {
    var presenter: WeatherInfoPresentationLogic?
    var worker: WeatherInfoWorker?
    var pageIndex: Int = 0
    var placemark: MKPlacemark? = nil
    
    // MARK: Do something
    
    func doSomething(request: WeatherInfo.Something.Request) {
        worker = WeatherInfoWorker()
        worker?.doSomeWork()
        
        let response = WeatherInfo.Something.Response()
        presenter?.presentSomething(response: response)
    }
}


