//
//  WeatherInfoWorker.swift
//  DarkSkyWeather
//
//  Created by rowkaxl on 10/08/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxCocoa
import MapKit

class WeatherInfoWorker {
    
    func requestDarkSkyWeather(apiKey: String, coordinate: CLLocationCoordinate2D) -> PrimitiveSequence<SingleTrait, APIResponseType> {
        return APIManager.request(target: .searchDarkSkyWeather(key: apiKey, langtitude: coordinate.latitude, longitude: coordinate.longitude))
    }
}

