//
//  WeatherInfoPresenter.swift
//  DarkSkyWeather
//
//  Created by rowkaxl on 10/08/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherInfoPresentationLogic {
    func presentSomething(response: WeatherInfo.Something.Response)
}

class WeatherInfoPresenter: WeatherInfoPresentationLogic {
    weak var viewController: WeatherInfoDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: WeatherInfo.Something.Response) {
        let viewModel = WeatherInfo.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}

