//
//  WeatherPresenter.swift
//  DarkSkyWeather
//
//  Created by rowkaxl on 07/08/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherPresentationLogic {
    func presentDarkSkyWeather(response: Weather.Info.Response)
}

class WeatherPresenter: WeatherPresentationLogic {
    weak var viewController: WeatherDisplayLogic?
    
    // MARK: Do something
    
    func presentDarkSkyWeather(response: Weather.Info.Response) {
        let viewModel = Weather.Info.ViewModel()
        viewController?.displayDarkSkyWeather(viewModel: viewModel)
    }
}

